"""add

Revision ID: 99cdbfe296ad
Revises: 6e307d602fec
Create Date: 2026-05-26 14:09:00.187726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '99cdbfe296ad'
down_revision = '6e307d602fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
